version: '3.8'

services:
  video-api:
    image: iamhuble/video-generator-api:latest
    volumes:
      - video_output:/app/output
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.video-api.rule=Host(`apivideo.efficore.es`)"
        - "traefik.http.routers.video-api.entrypoints=websecure"
        - "traefik.http.routers.video-api.tls.certresolver=le"
        - "traefik.http.services.video-api.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  video_output:
    driver: local

networks:
  traefik-public:
    external: true
